services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # Comment out volume if not actively developing inside container
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:5000/api
